const songs = [{
    id: 1,
    title: "Adekunle Gold - Damn, Delilah",
    src: require("../assets/music/Adekunle Gold - Damn, Delilah.mp3"),
    artist: ["Adekunle Gold"],
    date_modified: "13/03/2015",
    favourite: false,
    duration: "02:52",
  },
  {
    id: 2,
    title: "Adekunle Gold - Money",
    src: require("../assets/music/Adekunle Gold - Money.mp3"),
    artist: ["Adekunle Gold"],
    date_modified: "4/07/2017",
    favourite: false,
    duration: "03:07",
  },
  {
    id: 3,
    title: "Adekunle Gold - There Is A God",
    src: require("../assets/music/Adekunle Gold - There Is A God feat. LCGC.mp3"),
    artist: ["Adekunle Gold"],
    date_modified: "11/05/2017",
    favourite: false,
    duration: "04:04",
  },
  {
    id: 4,
    title: "Akon - Dont Matter",
    src: require("../assets/music/Akon - Dont Matter.mp3"),
    artist: ["Akon"],
    date_modified: "3/09/2011",
    favourite: false,
    duration: "04:05",
  },
  {
    id: 5,
    title: "John Legend - All Of Me",
    src: require("../assets/music/All Of Me.mp3"),
    artist: ["John Legend"],
    date_modified: "23/01/2016",
    favourite: false,
    duration: "04:29",
  },
  {
    id: 6,
    title: "Aza - Dmw",
    src: require("../assets/music/Aza - Dmw.mp3"),
    artist: ["Davido", "Duncan Mighty"],
    date_modified: "28/08/2016",
    favourite: false,
    duration: "03:45",
  },
  {
    id: 7,
    title: "B-Red Ft Phyno -Iwotago",
    src: require("../assets/music/B-Red Ft Phyno -Iwotago.mp3"),
    artist: ["B-Red", "Phyno"],
    date_modified: "28/02/2014",
    favourite: false,
    duration: "03:21",
  },
  {
    id: 8,
    title: "Beneath Your Beautiful - Dr Sid Ft Tiwa Savage",
    src: require("../assets/music/Beneath Your Beautiful -Dr Sid Ft Tiwa Savage.mp3"),
    artist: ["Dr Sid", "Tiwa Savage"],
    date_modified: "10/09/2014",
    favourite: false,
    duration: "04:28",
  },
  {
    id: 9,
    title: "Cardi B ft Bad Bunny & J Balvin - I Like It",
    src: require("../assets/music/Cardi B, Bad Bunny & J Balvin - I Like It.mp3"),
    artist: ["Cardi B", "Bad Bunny", "J Balvin"],
    date_modified: "12/03/2017",
    favourite: false,
    duration: "04:14",
  },
  {
    id: 10,
    title: "Ciara - Level Up",
    src: require("../assets/music/Ciara - Level Up.mp3"),
    artist: ["Ciara"],
    date_modified: "27/07/2016",
    favourite: false,
    duration: "03:31",
  },
  {
    id: 11,
    title: "demarco - i love my life",
    src: require("../assets/music/demarco - i love my life.mp3"),
    artist: ["Demarco"],
    date_modified: "7/04/2015",
    favourite: false,
    duration: "03:32",
  },
  {
    id: 12,
    title: "Despacito",
    src: require("../assets/music/Despacito.mp3"),
    artist: ["Luis Fonsi", "Daddy Yankee"],
    date_modified: "9/02/2018",
    favourite: false,
    duration: "03:48",
  },
  {
    id: 13,
    title: "DMW - Mind",
    src: require("../assets/music/DMW FEAT. DAVIDO, MAYORKUN, DREMO & PERUZZI - MIND.mp3"),
    artist: ["Davido", "Mayorkun", "Dremo", "Peruzzi"],
    date_modified: "19/08/2016",
    favourite: false,
    duration: "03:54",
  },
  {
    id: 14,
    title: "Drake - Gods Plan",
    src: require("../assets/music/Drake - Gods Plan.mp3"),
    artist: ["Drake"],
    date_modified: "12/10/2017",
    favourite: false,
    duration: "05:56",
  },
  {
    id: 15,
    title: "Eminem - River ft Ed Sheeran",
    src: require("../assets/music/Eminem - River ft. Ed Sheeran.mp3"),
    artist: ["Eminem"],
    date_modified: "06/10/2018",
    favourite: false,
    duration: "03:42",
  },
  {
    id: 16,
    title: "G-Eazy Ft Kehlani - Good Life",
    src: require("../assets/music/G-Eazy Ft Kehlani - Good Life.mp3"),
    artist: ["G-Eazy", "Kehlani"],
    date_modified: "26/02/2015",
    favourite: false,
    duration: "03:51",
  },
  {
    id: 17,
    title: "Ill be there - Mariah Carey",
    src: require("../assets/music/Ill be there.mp3"),
    artist: ["Mariah Carey"],
    date_modified: "6/08/2003",
    favourite: false,
    duration: "01:53",
  },
  {
    id: 18,
    title: "John Legend - Best you ever had",
    src: require("../assets/music/John Legend - Best you ever had.mp3"),
    artist: ["John Legend"],
    date_modified: "16/03/2013",
    favourite: false,
    duration: "04:04",
  },
  {
    id: 19,
    title: "Johnny Drille Ft Simi - Halleluya",
    src: require("../assets/music/Johnny Drille  Ft Simi - Halleluya.mp3"),
    artist: ["Johnny Drille", "Simi"],
    date_modified: "19/06/2017",
    favourite: false,
    duration: "03:54",
  },
  {
    id: 20,
    title: "Kiss Daniel - 4 days",
    src: require("../assets/music/Kiss Daniel - 4 days.mp3"),
    artist: ["Kiss Daniel"],
    date_modified: "11/08/2017",
    favourite: false,
    duration: "02:40",
  },
  {
    id: 21,
    title: "Kiss Daniel Ft Davido & Tiwa Savage – Woju Remix",
    src: require("../assets/music/Kiss Daniel Ft. Davido & Tiwa Savage – Woju Remix.mp3"),
    artist: ["Kiss Daniel", "Davido", "Tiwa Savage"],
    date_modified: "12/11/2016",
    favourite: false,
    duration: "03:24",
  },
  {
    id: 22,
    title: "Lil Dicky - Freaky Friday ft Chris Brown",
    src: require("../assets/music/Lil Dicky - Freaky Friday ft. Chris Brown.mp3"),
    artist: ["Chris Brown", "Lil Dicky"],
    date_modified: "18/12/2018",
    favourite: false,
    duration: "03:35",
  },
  {
    id: 24,
    title: "Lucky Dube - Teach the World",
    src: require("../assets/music/Lucky Dube-Teach the World.mp3"),
    artist: ["Lucky Dube"],
    date_modified: "13/07/2011",
    favourite: false,
    duration: "04:44",
  },
  {
    id: 25,
    title: "Luky Dube - Mama",
    src: require("../assets/music/Luky Dube - Mama.mp3"),
    artist: ["Lucky Dube"],
    date_modified: "18/03/2012",
    favourite: false,
    duration: "04:00",
  },
  {
    id: 26,
    title: "Major Lazer - Particula",
    src: require("../assets/music/Major Lazer - Particula (feat. Nasty C, Ice Prince, Patoranking & Jidenna).mp3"),
    artist: ["Major Lazer", "Nasty C", "Ice Prince", "Patoranking", "Jidenna"],
    date_modified: "13/02/2018",
    favourite: false,
    duration: "03:24",
  },
  {
    id: 27,
    title: "Mayorkun ft Davido - Bobo Lyrics",
    src: require("../assets/music/Mayorkun ft. Davido - Bobo Lyrics.mp3"),
    artist: ["Mayorkun", "Davido"],
    date_modified: "23/08/2018",
    favourite: false,
    duration: "03:32",
  },
  {
    id: 28,
    title: "Sean Kingston - Me Love",
    src: require("../assets/music/Me Love.mp3"),
    artist: ["Sean Kingston"],
    date_modified: "16/08/2007",
    favourite: false,
    duration: "03:24",
  },
  {
    id: 29,
    title: "Michael Jackson - Speechless",
    src: require("../assets/music/Michael Jackson - Speechless.mp3"),
    artist: ["Michael Jackson"],
    date_modified: "6/09/2006",
    favourite: false,
    duration: "03:20",
  },
  {
    id: 31,
    title: "Nonso Amadi - Tonight",
    src: require("../assets/music/Nonso Amadi - Tonight.mp3"),
    artist: ["Nonso Amadi"],
    date_modified: "11/11/2019",
    favourite: false,
    duration: "03:57",
  },
  {
    id: 32,
    title: "P-Square Ft 2face - Possibility",
    src: require("../assets/music/P-Square Ft 2face - Possibility.mp3"),
    artist: ["P-Square", "2face"],
    date_modified: "16/07/2016",
    favourite: false,
    duration: "05:07",
  },
  {
    id: 33,
    title: "P-Square ft Dave Scott_– Bring it on",
    src: require("../assets/music/P-Square ft Dave Scott_–Bring it on.mp3"),
    artist: ["P-Square", "Dave Scott"],
    date_modified: "18/03/2017",
    favourite: false,
    duration: "03:59",
  },
  {
    id: 34,
    title: "Patoranking - Suh Different",
    src: require("../assets/music/Patoranking - Suh Different.mp3"),
    artist: ["Patoranking"],
    date_modified: "30/04/2015",
    favourite: false,
    duration: "04:06",
  },
  {
    id: 35,
    title: "Perfect - Ed Sheeran",
    src: require("../assets/music/Perfect - Ed Sheeran.mp3"),
    artist: ["Ed Sheeran"],
    date_modified: "31/09/2016",
    favourite: false,
    duration: "04:28",
  },
  {
    id: 36,
    title: "P-Square - Ogadigide",
    src: require("../assets/music/Psquare - Ogadigide.mp3"),
    artist: ["P-Square"],
    date_modified: "31/09/2016",
    favourite: false,
    duration: "04:12",
  },
  {
    id: 37,
    title: "P-Square - forever",
    src: require("../assets/music/Psquare- forever.mp3"),
    artist: ["P-Square"],
    date_modified: "03/05/2017",
    favourite: false,
    duration: "04:29",
  },
  {
    id: 38,
    title: "Sean Kingston Ft Lil Wayne - Im At War",
    src: require("../assets/music/Sean Kingston Ft Lil Wayne - Im At War.mp3"),
    artist: ["Sean Kingston", "Lil Wayne"],
    date_modified: "02/01/2018",
    favourite: false,
    duration: "03:45",
  },
  {
    id: 39,
    title: "Seyi Shay - Right Now (Remix)",
    src: require("../assets/music/Seyi Shay - Right Now (Remix) ft. Iyanya & Banky W.mp3"),
    artist: ["Seyi Shay", "Iyanya", "Banky W"],
    date_modified: "12/07/2018",
    favourite: false,
    duration: "03:35",
  },
  {
    id: 40,
    title: "Shaggy - Angel ft Rayvon",
    src: require("../assets/music/Shaggy - Angel ft. Rayvon.mp3"),
    artist: ["Shaggy", "Rayvon"],
    date_modified: "24/08/2015",
    favourite: false,
    duration: "03:56",
  },
  {
    id: 41,
    title: "Simi ft 2face - Original Baby (Remix)",
    src: require("../assets/music/Simi ft. 2baba - Original Baby (Remix).mp3"),
    artist: ["Shaggy", "Rayvon"],
    date_modified: "24/08/2015",
    favourite: false,
    duration: "03:57",
  },
  {
    id: 42,
    title: "Tiwa Savage Ft Reminisce & Slimcase  - Diet",
    src: require("../assets/music/Tiwa Savage Ft Reminisce , Slimcase  - Diet.mp3"),
    artist: ["Tiwa Savage", "Reminisce", "Slimcase"],
    date_modified: "21/03/2019",
    favourite: false,
    duration: "03:20",
  },
  {
    id: 43,
    title: "Usher - Moving Mountains",
    src: require("../assets/music/Usher - Moving Mountains.mp3"),
    artist: ["Usher"],
    date_modified: "14/05/2013",
    favourite: false,
    duration: "05:05",
  },
];

export default {
  songs() {
    return songs;
  },
};